# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_cash_register', '0004_auto_20170206_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ym_merchant_receipt',
            field=models.TextField(blank=True, null=True, verbose_name='ym_merchant_receipt'),
        ),
    ]
